projects:
  themeetinghouse:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
      - src/pages/admin/queries.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 7
extensions:
  amplify:
    version: 3
