projects:
  meetinghouse:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: freaaighnbcjhksw63ci4fgjxu
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        maxDepth: 10
      endpoints:
        prod: >-
          https://chx7bfj4sbgtfoam6myzmyhafu.appsync-api.us-east-1.amazonaws.com/graphql
